### PR TITLE
added example by integrating `createdAt`

### PR DESCRIPTION
**Pull request by teoEnache**

### CODE REVIEW

**Review by chrieke — APPROVED** [review]
Might be good to say something like "Available sorting criteria are the properties of the response etc. " or maybe even adding more examples of the possible sorting criteria, see https://sdk.up42.com/reference/storage-reference/ (different for orders/assets though).

**Comment by teoEnache** [comment]
@chrieke thank you for the examples. I tried using `sort=source` and it gives a 500 server error. Can you confirm that all the examples written in the SDK docs work as expected?

**Comment by chrieke** [comment]
@teoEnache Good point, not every results contains all the properties, "source" seems to be one that only works for queries in some workspaces, the assets/orders are not consistent in their metadata across the board. The rest worked for me on 3 workspaces, source only on one. I still included it for now, is bookmarked and will take it uo with backend at some point.

**Comment by teoEnache** [comment]
@chrieke if it's OK for you, I will abstain from uncluding `source` for now :)

**Comment by chrieke** [comment]
@teoEnache Makes sense

**Comment by teoEnache** [comment]
@chrieke does it look better now?

**Review by chrieke — DISMISSED** [review]
Can't say how this is rendered as intended etc, only checked parameter selection.

Parameters LGTM except `type` missing for SortOrders. Could you check if this is available or maybe an error when adding it to the SDK.

**Comment by teoEnache** [comment]
@chrieke the sorting criteria `type` does not seem to work. Have you tried it?

**Comment by teoEnache** [comment]
@aposiker the percent-encoding was removed with `allowReserved`

**Review by aposiker — APPROVED** [review]

**Pull request merged**
